Repository php/doc-en, pull requests merged in 2021-11, with the labels that each got.

#1039 [PHP 8.1] Add cURL constants
  reference/curl/constants.xml
Labels: Waiting on Review

#1018 [PHP 8.1] Add new Sockets constants
  reference/sockets/constants.xml
  reference/sockets/functions/socket-get-option.xml
Labels: Waiting on Review, next milestone

#1064 Generate ext/com_dotnet class synopses from stubs
  reference/com/com-exception.xml
  reference/com/com.xml
  reference/com/compersisthelper.xml
  reference/com/dotnet.xml
  reference/com/variant.xml
Labels: method synopsis

#650 Fix 80971: func_get_args() didnt work when using named args
  language-snippets.ent
  reference/funchand/functions/func-get-arg.xml
  reference/funchand/functions/func-get-args.xml
  reference/funchand/functions/func-num-args.xml
Labels: Waiting on Review

#1071 Generate ext/sqlite3 class synopses from stubs
  reference/sqlite3/sqlite3.xml
  reference/sqlite3/sqlite3result.xml
  reference/sqlite3/sqlite3result/construct.xml
  reference/sqlite3/sqlite3stmt.xml
  reference/sqlite3/sqlite3stmt/construct.xml
Labels: method synopsis

#1074 Generate ext/openssl class synopses from stubs
  reference/openssl/opensslasymmetrickey.xml
  reference/openssl/opensslcertificate.xml
  reference/openssl/opensslcertificatesigningrequest.xml
Labels: method synopsis

#1075 Generate ext/enchant class synopses from stubs
  reference/enchant/enchantbroker.xml
  reference/enchant/enchantdictionary.xml
Labels: method synopsis

#1073 Generate ext/pspell class synopses from stubs
  reference/pspell/pspell.config.xml
  reference/pspell/pspell.dictionary.xml
Labels: method synopsis

#1072 Generate ext/sodium class synopses from stubs
  reference/sodium/sodiumexception.xml
Labels: method synopsis

#1070 Generate ext/tidy class synopses from stubs
  reference/tidy/tidy.xml
Labels: method synopsis

#1069 Generate ext/tokenizer class synopses from stubs
  reference/tokenizer/phptoken.xml
Labels: method synopsis

#1067 Generate ext/xsl class synopses from stubs
  reference/xsl/xsltprocessor.xml
Labels: method synopsis

#1103 Generate ext/sockets class synopses from stubs
  reference/sockets/addressinfo.xml
  reference/sockets/socket.xml
Labels: method synopsis

#1108 [skip-revcheck] Generate ext/sysvsem class synopses from stubs
  reference/sem/sysvsemaphore.xml
Labels: method synopsis

#1110 [skip-revcheck] Generate ext/pgsql class synopses from stubs
  reference/pgsql/pgsql.connection.xml
  reference/pgsql/pgsql.lob.xml
  reference/pgsql/pgsql.result.xml
Labels: method synopsis

#1111 [skip-revcheck] Generate ext/ldap class synopses from stubs
  reference/ldap/ldap.connection.xml
  reference/ldap/ldap.result.xml
  reference/ldap/ldap.resultentry.xml
Labels: method synopsis

#1114 [skip-revcheck] Generate ext/ftp class synopses from stubs
  reference/ftp/ftp.connection.xml
Labels: method synopsis

#1118 [skip-revcheck] Generate ext/imap class synopses from stubs
  reference/imap/imap.connection.xml
Labels: method synopsis

#1115 [skip-revcheck] Generate ext/fileinfo class synospes from stubs
  reference/fileinfo/finfo.xml
Labels: method synopsis

#1065 Generate ext/zlib class synopses from stubs
  reference/zlib/deflatecontext.xml
  reference/zlib/inflatecontext.xml
Labels: method synopsis

#1106 [skip-revcheck] Generate ext/shmop class synopses from stubs
  reference/shmop/shmop.xml
Labels: method synopsis

#1104 [skip-revcheck] Generate ext/json class synopses from stubs
  reference/json/jsonexception.xml
  reference/json/jsonserializable.xml
Labels: method synopsis

#1112 Generate ext/curl class synopses from stubs
  reference/curl/curlfile.xml
  reference/curl/curlhandle.xml
  reference/curl/curlmultihandle.xml
  reference/curl/curlsharehandle.xml
Labels: method synopsis

#1120 Generate ext/reflection class synopses from stubs - part 1
  reference/reflection/reflectionparameter.xml
  reference/reflection/reflectionproperty.xml
  reference/reflection/reflectionreference.xml
  reference/reflection/reflectiontype.xml
  reference/reflection/reflectionuniontype.xml
  reference/reflection/reflectionzendextension.xml
Labels: method synopsis

#1121 Generate ext/reflection class synopses from stubs - part 2
  reference/reflection/reflection.xml
  reference/reflection/reflectionattribute.xml
  reference/reflection/reflectionclass.xml
  reference/reflection/reflectionclassconstant.xml
  reference/reflection/reflectionexception.xml
  reference/reflection/reflectionextension.xml
Labels: method synopsis

#1127 Document returning by reference from a void function deprecation.
  language/types/declarations.xml
Labels: Waiting on Review

#1137 Add docs for ReflectionReference::__construct()
  reference/reflection/reflectionreference.xml
  reference/reflection/reflectionreference/construct.xml
Labels: method synopsis

#1126 Document autovivification from false deprecation.
  language/types/array.xml
Labels: Waiting on Review

#1154 [PHP 8.1] Document CURLStringFile
  reference/curl/book.xml
  reference/curl/curlstringfile.xml
  reference/curl/curlstringfile/construct.xml
  reference/curl/versions.xml
Labels: Waiting on Review

#1147 [PHP 8.1] Document restriction of $GLOBALS usage.
  language/predefined/variables/globals.xml
Labels: Waiting on Author, Waiting on Review
