Repository php/doc-en, pull requests merged in 2021-12, with the labels that each got.

#1138 Generate ext/reflection class synopses from stubs - part 3
  reference/reflection/reflectionenum.xml
  reference/reflection/reflectionenum/construct.xml
  reference/reflection/reflectionenumbackedcase.xml
  reference/reflection/reflectionenumbackedcase/construct.xml
  reference/reflection/reflectionenumunitcase.xml
  reference/reflection/reflectionenumunitcase/construct.xml
  reference/reflection/versions.xml
Labels: method synopsis

#1171 [PHP 8.1] Document Array Unpacking with [int|string] Keys.
  appendices/migration81/new-features.xml
  language/types/array.xml
Labels: Waiting on Review

#1179 [PHP 8.1] Document deprecated ctype non-string argument.
  appendices/migration81/deprecated.xml
  language-snippets.ent
  reference/ctype/functions/ctype-alnum.xml
  reference/ctype/functions/ctype-alpha.xml
  reference/ctype/functions/ctype-cntrl.xml
  reference/ctype/functions/ctype-digit.xml
  reference/ctype/functions/ctype-graph.xml
  reference/ctype/functions/ctype-lower.xml
  reference/ctype/functions/ctype-print.xml
  reference/ctype/functions/ctype-punct.xml
  reference/ctype/functions/ctype-space.xml
  reference/ctype/functions/ctype-upper.xml
  reference/ctype/functions/ctype-xdigit.xml
Labels: Waiting on Review

#1130 [PHP 8.1] Documentation for `full_path` entry of `$_FILES`
  features/file-upload.xml
Labels: Waiting on Review

#1105 [skip-revcheck] Generate ext/oci8 class synopses from stubs
  reference/oci8/OCI-Collection.xml
  reference/oci8/OCI-Lob.xml
Labels: method synopsis

#1119 Generate ext/snmp class synopses from stubs
  reference/snmp/snmp.xml
  reference/snmp/snmpexception.xml
Labels: method synopsis

#1068 Generate ext/xmlreader and ext/xmlwriter class synopses from stubs
  reference/xmlreader/xmlreader.xml
  reference/xmlwriter/xmlwriter.xml
Labels: method synopsis

#1066 Generate ext/zip class synopses from stubs
  reference/zip/ziparchive.xml
Labels: method synopsis

#1021 Generate a few ext/standard method synopses based on stubs - part 3
  reference/stream/functions/stream-get-contents.xml
  reference/stream/functions/stream-get-line.xml
  reference/stream/functions/stream-select.xml
  reference/stream/functions/stream-set-write-buffer.xml
  reference/stream/functions/stream-socket-accept.xml
  reference/stream/functions/stream-socket-client.xml
  reference/stream/functions/stream-socket-enable-crypto.xml
Labels: method synopsis, Waiting on Review

#1207 Fix a few enum function/method signatures
  reference/classobj/functions/enum-exists.xml
  reference/reflection/reflectionenumbackedcase/construct.xml
  reference/reflection/reflectionenumbackedcase/getbackingvalue.xml
  reference/reflection/reflectionenumunitcase/construct.xml
Labels: method synopsis

#1208 Fix a few ext/reflection return types
  reference/reflection/reflectionclass/newinstanceargs.xml
  reference/reflection/reflectionclassconstant/getname.xml
Labels: method synopsis

#1213 Regenerate ext/curl method synopses
  reference/curl/curlstringfile/construct.xml
Labels: method synopsis

#1140 Generate ext/reflection class synopses from stubs - part 5
  reference/reflection/reflectionintersectiontype.xml
  reference/reflection/reflectionnamedtype.xml
  reference/reflection/reflectionobject.xml
  reference/reflection/reflectionproperty.xml
Labels: method synopsis

#1222 Generate ext/spl class synopses from stubs - part 1
  reference/spl/splqueue.xml
  reference/spl/splstack.xml
  reference/spl/splsubject.xml
  reference/spl/spltempfileobject.xml
  reference/spl/underflowexception.xml
  reference/spl/unexpectedvalueexception.xml
Labels: method synopsis

#1223 Generate ext/spl class synopses from stubs - part 2
  reference/spl/splheap.xml
  reference/spl/splmaxheap.xml
  reference/spl/splminheap.xml
  reference/spl/splobjectstorage.xml
  reference/spl/splobserver.xml
  reference/spl/splpriorityqueue.xml
Labels: method synopsis

#1224 Generate ext/spl class synopses from stubs - part 3
  reference/spl/recursivetreeiterator.xml
  reference/spl/regexiterator.xml
  reference/spl/runtimeexception.xml
  reference/spl/seekableiterator.xml
  reference/spl/spldoublylinkedlist.xml
  reference/spl/splfileinfo.xml
  reference/spl/splfileobject.xml
  reference/spl/splfixedarray.xml
Labels: method synopsis

#1225 Fix $message_nums parameter names
  reference/imap/functions/imap-delete.xml
  reference/imap/functions/imap-undelete.xml
Labels: method synopsis

#1226 Generate ext/ffi class synopses from stubs
  reference/ffi/ffi.cdata.xml
  reference/ffi/ffi.ctype.xml
  reference/ffi/ffi.exception.xml
  reference/ffi/ffi.parserexception.xml
  reference/ffi/ffi.xml
Labels: method synopsis

#1232 Generate various ext/standard method synopses from stubs - part 5
  reference/errorfunc/functions/error-log.xml
  reference/errorfunc/functions/set-error-handler.xml
  reference/errorfunc/functions/set-exception-handler.xml
  reference/exec/functions/proc-open.xml
  reference/strings/functions/str-getcsv.xml
  reference/url/functions/get-headers.xml
  reference/url/functions/parse-url.xml
Labels: method synopsis

#1235 Generate ext/spl class synopses from stubs - part 4
  reference/spl/appenditerator.xml
  reference/spl/arrayiterator.xml
  reference/spl/arrayobject.xml
  reference/spl/badfunctioncallexception.xml
  reference/spl/badmethodcallexception.xml
  reference/spl/cachingiterator.xml
  reference/spl/callbackfilteriterator.xml
  reference/spl/countable.xml
  reference/spl/directoryiterator.xml
Labels: method synopsis

#1236 Generate ext/spl class synopses from stubs - part 5
  reference/spl/emptyiterator.xml
  reference/spl/filesystemiterator.xml
  reference/spl/filteriterator.xml
  reference/spl/globiterator.xml
  reference/spl/infiniteiterator.xml
  reference/spl/iteratoriterator.xml
  reference/spl/norewinditerator.xml
  reference/spl/outeriterator.xml
Labels: method synopsis

#1234 Generate various method synopses from stubs - part 5
  reference/ftp/functions/ftp-raw.xml
  reference/image/functions/imagecolorsforindex.xml
  reference/info/functions/ini-set.xml
  reference/openssl/functions/openssl-cms-encrypt.xml
  reference/openssl/functions/openssl-decrypt.xml
  reference/openssl/functions/openssl-pkcs7-encrypt.xml
  reference/pdo/pdo/getattribute.xml
  reference/spl/splobjectstorage/current.xml
Labels: method synopsis

#931 Clean up filesystem function signatures
  reference/filesystem/functions/copy.xml
  reference/filesystem/functions/fgets.xml
  reference/filesystem/functions/file-get-contents.xml
  reference/filesystem/functions/file-put-contents.xml
  reference/filesystem/functions/file.xml
  reference/filesystem/functions/fopen.xml
  reference/filesystem/functions/fwrite.xml
  reference/filesystem/functions/mkdir.xml
  reference/filesystem/functions/readfile.xml
  reference/filesystem/functions/rename.xml
  reference/filesystem/functions/rmdir.xml
  reference/filesystem/functions/touch.xml
  reference/filesystem/functions/umask.xml
  reference/filesystem/functions/unlink.xml
Labels: method synopsis

#1242 Generate ext/spl class synopses from stubs - part 6
  reference/spl/domainexception.xml
  reference/spl/invalidargumentexception.xml
  reference/spl/lengthexception.xml
  reference/spl/logicexception.xml
  reference/spl/outofboundsexception.xml
  reference/spl/outofrangeexception.xml
  reference/spl/overflowexception.xml
  reference/spl/rangeexception.xml
Labels: method synopsis

#1243 Generate ext/spl class synopses from stubs - part 7
  reference/spl/limititerator.xml
  reference/spl/multipleiterator.xml
  reference/spl/outeriterator.xml
  reference/spl/parentiterator.xml
  reference/spl/recursivearrayiterator.xml
  reference/spl/recursivecachingiterator.xml
  reference/spl/recursivecallbackfilteriterator.xml
  reference/spl/recursivedirectoryiterator.xml
  reference/spl/recursivefilteriterator.xml
  reference/spl/recursiveiterator.xml
  reference/spl/recursiveiteratoriterator.xml
Labels: method synopsis

#1241 Generate various class synopses from stubs - part 1
  reference/reflection/reflectionfiber.xml
  reference/sem/sysvmessagequeue.xml
  reference/sem/sysvsharedmemory.xml
  reference/simplexml/simplexmlelement.xml
  reference/simplexml/simplexmliterator.xml
Labels: method synopsis

#1245 Generate Zend class synopses from stubs - part 2
  language/predefined/generator.xml
  language/predefined/iterator.xml
  language/predefined/iteratoraggregate.xml
  language/predefined/parseerror.xml
  language/predefined/serializable.xml
  language/predefined/stringable.xml
  language/predefined/throwable.xml
  language/predefined/traversable.xml
  language/predefined/typeerror.xml
  language/predefined/unhandledmatcherror.xml
  language/predefined/unitenum.xml
  language/predefined/valueerror.xml
  language/predefined/weakmap.xml
  language/predefined/weakreference.xml
Labels: method synopsis

#1247 Generate ext/date class synopses from stubs
  reference/datetime/dateinterval.xml
  reference/datetime/dateperiod.xml
  reference/datetime/datetime.xml
  reference/datetime/datetimeimmutable.xml
  reference/datetime/datetimeinterface.xml
  reference/datetime/datetimezone.xml
Labels: method synopsis

#1248 Generate ext/intl classsynopses from stubs - part 1
  reference/intl/intlcalendar.xml
  reference/intl/intliterator.xml
  reference/intl/intltimezone.xml
  reference/intl/intltimezone/construct.xml
  reference/intl/locale.xml
  reference/intl/normalizer.xml
  reference/intl/numberformatter.xml
Labels: method synopsis

#1250 Generate ext/dom class synopses from stubs - part 1
  reference/dom/domcdatasection.xml
  reference/dom/domcomment.xml
  reference/dom/domentityreference.xml
  reference/dom/domexception.xml
  reference/dom/domimplementation.xml
  reference/dom/domnamednodemap.xml
  reference/dom/domnode.xml
  reference/dom/domnodelist.xml
  reference/dom/domnotation.xml
  reference/dom/domprocessinginstruction.xml
  reference/dom/domtext.xml
Labels: method synopsis

#1249 Generate ext/intl class synopses from stubs - part 2
  reference/intl/collator.xml
  reference/intl/dateformatter.xml
  reference/intl/intlbreakiterator.xml
  reference/intl/intlchar.xml
  reference/intl/intlexception.xml
  reference/intl/messageformatter.xml
  reference/intl/transliterator.xml
Labels: method synopsis

#1260 Regenerate Exception class and method synopses from stubs
  language/predefined/error.xml
  language/predefined/error/clone.xml
  language/predefined/exception.xml
  language/predefined/exception/clone.xml
Labels: method synopsis

#1259 Fix ext/dom method synopses
  reference/dom/domdocument/createcomment.xml
  reference/dom/domdocument/createdocumentfragment.xml
  reference/dom/domdocument/createtextnode.xml
  reference/dom/domnamednodemap/count.xml
  reference/dom/domnodelist/count.xml
  reference/dom/domnodelist/item.xml
Labels: method synopsis

#1258 Remove unnecessary DateInterval, DatePeriod, DateTime and DateTimeZone method synopsis roles
  reference/datetime/dateinterval/construct.xml
  reference/datetime/dateperiod/getdateinterval.xml
  reference/datetime/dateperiod/getenddate.xml
  reference/datetime/dateperiod/getrecurrences.xml
  reference/datetime/dateperiod/getstartdate.xml
  reference/datetime/datetime/construct.xml
  reference/datetime/datetime/createfromimmutable.xml
  reference/datetime/datetime/createfrominterface.xml
  reference/datetime/datetime/set-state.xml
  reference/datetime/datetimezone/construct.xml
Labels: method synopsis

#1257 Remove unnecessary DateTimeImmutable method synopsis roles
  reference/datetime/datetimeimmutable/add.xml
  reference/datetime/datetimeimmutable/construct.xml
  reference/datetime/datetimeimmutable/createfrominterface.xml
  reference/datetime/datetimeimmutable/createfrommutable.xml
  reference/datetime/datetimeimmutable/modify.xml
  reference/datetime/datetimeimmutable/set-state.xml
  reference/datetime/datetimeimmutable/setdate.xml
  reference/datetime/datetimeimmutable/setisodate.xml
  reference/datetime/datetimeimmutable/settime.xml
  reference/datetime/datetimeimmutable/settimestamp.xml
  reference/datetime/datetimeimmutable/settimezone.xml
  reference/datetime/datetimeimmutable/sub.xml
Labels: method synopsis

#1251 Generate various class synopses from stubs - part 2
  language/predefined/errorexception.xml
  language/predefined/fiber.xml
  language/predefined/fibererror.xml
  language/predefined/fibererror/construct.xml
  language/predefined/versions.xml
  reference/dir/directory.xml
  reference/mysqli/mysqli_sql_exception.xml
  reference/snmp/snmp.xml
  reference/spl/recursiveregexiterator.xml
Labels: method synopsis

#1261 Regenerate ext/phar method synopses based on stubs
  reference/phar/Phar/buildFromDirectory.xml
  reference/phar/Phar/buildFromIterator.xml
  reference/phar/Phar/copy.xml
  reference/phar/Phar/offsetGet.xml
  reference/phar/Phar/offsetUnset.xml
  reference/phar/PharData/buildFromDirectory.xml
  reference/phar/PharData/buildFromIterator.xml
  reference/phar/PharData/copy.xml
  reference/phar/PharData/offsetUnset.xml
Labels: method synopsis

#1256 Generate ext/phar class synopses from stubs
  reference/phar/Phar.xml
  reference/phar/Phar/destruct.xml
  reference/phar/PharData.xml
  reference/phar/PharData/destruct.xml
  reference/phar/PharException.xml
  reference/phar/PharFileInfo.xml
  reference/phar/PharFileInfo/destruct.xml
  reference/phar/versions.xml
Labels: method synopsis

#912 Generate ext/intl methodsynopses based on stubs (IntlGregorianCalendar, IntlIterator, IntlRuleBasedBreakIterator)
  reference/intl/intlgregoriancalendar/getgregorianchange.xml
  reference/intl/intlgregoriancalendar/isleapyear.xml
  reference/intl/intlgregoriancalendar/setgregorianchange.xml
  reference/intl/intliterator/key.xml
  reference/intl/intlrulebasedbreakiterator.xml
  reference/intl/intlrulebasedbreakiterator/construct.xml
  reference/intl/intlrulebasedbreakiterator/getbinaryrules.xml
  reference/intl/intlrulebasedbreakiterator/getrules.xml
  reference/intl/intlrulebasedbreakiterator/getrulestatusvec.xml
Labels: method synopsis

#1268 Update the signature of fgetcsv() and fputcsv()
  reference/filesystem/functions/fgetcsv.xml
  reference/filesystem/functions/fputcsv.xml
Labels: method synopsis

#1176 [PHP 8.1] Document the first class callable syntax.
  appendices/migration81/new-features.xml
  language/functions.xml
  language/predefined/closure/fromcallable.xml
  language/types/callable.xml
Labels: Waiting on Review

#1269 Fix fgetcsv() return value section
  reference/filesystem/functions/fgetcsv.xml
Labels: method synopsis

#1274 Generate ext/intl class synopses from stubs - part 3
  reference/intl/intlcodepointbreakiterator.xml
  reference/intl/intlgregoriancalendar.xml
  reference/intl/intlpartsiterator.xml
  reference/intl/intlrulebasedbreakiterator.xml
  reference/intl/resourcebundle.xml
  reference/intl/spoofchecker.xml
  reference/intl/uconverter.xml
Labels: method synopsis

#1273 Regenerate ext/spl method synopses based on stubs
  reference/spl/arrayiterator/key.xml
  reference/spl/emptyiterator/current.xml
  reference/spl/emptyiterator/key.xml
  reference/spl/multipleiterator/current.xml
  reference/spl/multipleiterator/key.xml
  reference/spl/recursiveiteratoriterator/callhaschildren.xml
Labels: method synopsis

#1272 Update some string function parameter default values
  reference/strings/functions/get-html-translation-table.xml
  reference/strings/functions/html-entity-decode.xml
  reference/strings/functions/htmlentities.xml
  reference/strings/functions/htmlspecialchars-decode.xml
  reference/strings/functions/htmlspecialchars.xml
  reference/strings/functions/ltrim.xml
  reference/strings/functions/rtrim.xml
  reference/strings/functions/trim.xml
Labels: method synopsis
