Repository php/doc-en, pull requests merged in 2021-10, with the labels that each got.

#903 Generate methodsynopses based on stubs for recent changes
  reference/dir/directory/close.xml
  reference/dir/directory/read.xml
  reference/dir/directory/rewind.xml
  reference/dir/functions/closedir.xml
  reference/dir/functions/dir.xml
  reference/dir/functions/opendir.xml
  reference/dir/functions/readdir.xml
  reference/dir/functions/rewinddir.xml
  reference/dir/functions/scandir.xml
  reference/dom/domelement/getattributenode.xml
  reference/dom/domelement/getattributenodens.xml
  reference/ldap/functions/ldap-connect.xml
  reference/mysqli/mysqli/get-client-info.xml
  reference/mysqli/mysqli/init.xml
  reference/reflection/reflectionclass/getattributes.xml
  reference/reflection/reflectionclassconstant/getattributes.xml
  reference/reflection/reflectionfunctionabstract/getattributes.xml
  reference/reflection/reflectionparameter/getattributes.xml
  reference/reflection/reflectionproperty/getattributes.xml
  reference/session/sessionhandler/gc.xml
  reference/snmp/functions/snmp2-get.xml
  reference/snmp/functions/snmp2-getnext.xml
  reference/snmp/functions/snmp2-real-walk.xml
  reference/snmp/functions/snmp2-set.xml
  reference/snmp/functions/snmp2-walk.xml
  reference/snmp/functions/snmp3-get.xml
  reference/snmp/functions/snmp3-getnext.xml
  reference/snmp/functions/snmp3-real-walk.xml
  reference/snmp/functions/snmp3-set.xml
  reference/snmp/functions/snmp3-walk.xml
  reference/snmp/functions/snmpget.xml
  reference/snmp/functions/snmpgetnext.xml
  reference/snmp/functions/snmprealwalk.xml
  reference/snmp/functions/snmpset.xml
  reference/snmp/functions/snmpwalk.xml
  reference/snmp/functions/snmpwalkoid.xml
  reference/snmp/snmp/getnext.xml
  reference/snmp/snmp/set.xml
  reference/snmp/snmp/walk.xml
Labels: method synopsis, Waiting on Review

#987 [PHP 8.1] Update `mysqli_stmt::execute` description
  reference/mysqli/mysqli_stmt/execute.xml
Labels: Waiting on Review, next milestone

#986 [PHP 8.1] Add `array_is_list` description
  reference/array/functions/array-is-list.xml
  reference/array/versions.xml
Labels: Waiting on Review, next milestone

#994 [PHP 8.1] Use GdFont
  appendices/resources.xml
  language-snippets.ent
  reference/image/book.xml
  reference/image/functions/imagechar.xml
  reference/image/functions/imagecharup.xml
  reference/image/functions/imagefontheight.xml
  reference/image/functions/imagefontwidth.xml
  reference/image/functions/imageloadfont.xml
  reference/image/functions/imagestring.xml
  reference/image/functions/imagestringup.xml
  reference/image/gdfont.xml
  reference/image/setup.xml
  reference/image/versions.xml
Labels: next milestone

#904 Generate methodsynopses from stubs for ext/intl (IntlBreakIterator)
  reference/intl/intlbreakiterator.xml
  reference/intl/intlbreakiterator/construct.xml
  reference/intl/intlbreakiterator/createcharacterinstance.xml
  reference/intl/intlbreakiterator/createcodepointinstance.xml
  reference/intl/intlbreakiterator/createlineinstance.xml
  reference/intl/intlbreakiterator/createsentenceinstance.xml
  reference/intl/intlbreakiterator/createtitleinstance.xml
  reference/intl/intlbreakiterator/createwordinstance.xml
  reference/intl/intlbreakiterator/geterrormessage.xml
  reference/intl/intlbreakiterator/getlocale.xml
  reference/intl/intlbreakiterator/getpartsiterator.xml
  reference/intl/intlbreakiterator/gettext.xml
  reference/intl/intlbreakiterator/next.xml
  reference/intl/intlbreakiterator/settext.xml
Labels: method synopsis, Waiting on Review

#1002 [PHP 8.1] Add `fdatasync` and `fsync` description
  reference/filesystem/functions/fdatasync.xml
  reference/filesystem/functions/fsync.xml
  reference/filesystem/versions.xml
Labels: next milestone

#841 Clarification of return values descriptions for mysqi fetch functions
  reference/mysqli/mysqli_result/fetch-array.xml
  reference/mysqli/mysqli_result/fetch-assoc.xml
  reference/mysqli/mysqli_result/fetch-object.xml
  reference/mysqli/mysqli_result/fetch-row.xml
Labels: Waiting on Author
