Repository php/doc-en, pull requests merged in 2021-09, with the labels that each got.

#906 Generate ext/intl methodsynopses from stubs (UConverter)
  reference/intl/uconverter.xml
  reference/intl/uconverter/construct.xml
  reference/intl/uconverter/convert.xml
  reference/intl/uconverter/fromucallback.xml
  reference/intl/uconverter/getaliases.xml
  reference/intl/uconverter/getdestinationencoding.xml
  reference/intl/uconverter/getdestinationtype.xml
  reference/intl/uconverter/geterrormessage.xml
  reference/intl/uconverter/getsourceencoding.xml
  reference/intl/uconverter/getsourcetype.xml
  reference/intl/uconverter/getstandards.xml
  reference/intl/uconverter/getsubstchars.xml
  reference/intl/uconverter/reasontext.xml
  reference/intl/uconverter/setdestinationencoding.xml
  reference/intl/uconverter/setsourceencoding.xml
  reference/intl/uconverter/setsubstchars.xml
  reference/intl/uconverter/toucallback.xml
  reference/intl/uconverter/transcode.xml
Labels: method synopsis

#914 Remove some unnecessary abstract modifiers from methodsynopses
  language/predefined/iterator/current.xml
  language/predefined/iterator/key.xml
  language/predefined/iterator/next.xml
  language/predefined/iterator/rewind.xml
  language/predefined/iterator/valid.xml
  language/predefined/iteratoraggregate/getiterator.xml
  language/predefined/serializable/serialize.xml
  language/predefined/serializable/unserialize.xml
  language/predefined/throwable/getcode.xml
  language/predefined/throwable/getfile.xml
  language/predefined/throwable/getline.xml
  language/predefined/throwable/getmessage.xml
  language/predefined/throwable/getprevious.xml
  language/predefined/throwable/gettrace.xml
  language/predefined/throwable/gettraceasstring.xml
  language/predefined/weakmap/getiterator.xml
  reference/json/jsonserializable/jsonserialize.xml
  reference/session/sessionhandlerinterface/close.xml
  reference/session/sessionhandlerinterface/destroy.xml
  reference/session/sessionhandlerinterface/gc.xml
  reference/session/sessionhandlerinterface/open.xml
  reference/session/sessionhandlerinterface/write.xml
  reference/session/sessionidinterface/create-sid.xml
  reference/session/sessionupdatetimestamphandlerinterface/updatetimestamp.xml
  reference/session/sessionupdatetimestamphandlerinterface/validateid.xml
Labels: method synopsis

#913 Remove some unnecessary methodsynopsis role attributes
  reference/com/com/construct.xml
  reference/com/dotnet/construct.xml
  reference/com/variant/construct.xml
  reference/csprng/functions/random-bytes.xml
  reference/csprng/functions/random-int.xml
  reference/curl/curlfile/construct.xml
  reference/curl/functions/curl-multi-errno.xml
  reference/hash/functions/hash-hmac-algos.xml
  reference/hash/functions/hash-pbkdf2.xml
  reference/image/functions/imagesetclip.xml
  reference/imap/functions/imap-mutf7-to-utf8.xml
  reference/imap/functions/imap-utf8-to-mutf7.xml
  reference/misc/functions/sapi-windows-cp-conv.xml
  reference/misc/functions/sapi-windows-cp-get.xml
  reference/misc/functions/sapi-windows-cp-is-utf8.xml
  reference/misc/functions/sapi-windows-cp-set.xml
  reference/misc/functions/sapi-windows-vt100-support.xml
  reference/network/functions/setcookie.xml
  reference/network/functions/setrawcookie.xml
  reference/openssl/functions/openssl-spki-export-challenge.xml
  reference/openssl/functions/openssl-spki-export.xml
  reference/openssl/functions/openssl-spki-new.xml
  reference/openssl/functions/openssl-spki-verify.xml
  reference/snmp/snmp/close.xml
  reference/snmp/snmp/get.xml
  reference/snmp/snmp/geterrno.xml
  reference/snmp/snmp/geterror.xml
  reference/snmp/snmp/getnext.xml
  reference/snmp/snmp/set.xml
  reference/snmp/snmp/setsecurity.xml
  reference/snmp/snmp/walk.xml
  reference/sqlite3/sqlite3/enableExceptions.xml
  reference/zip/ziparchive/addglob.xml
  reference/zip/ziparchive/addpattern.xml
Labels: method synopsis

#953 Add `get_mangled_object_vars` description
  reference/classobj/functions/get-mangled-object-vars.xml
  reference/classobj/versions.xml
Labels: Waiting on Review

#692 fixed localtime returnvalues description.
  reference/datetime/functions/localtime.xml
Labels: Waiting on Review

#289 Generate some standard methodsynopses based on stubs
  reference/exec/functions/passthru.xml
  reference/exec/functions/shell-exec.xml
  reference/funchand/functions/register-shutdown-function.xml
  reference/math/functions/pow.xml
  reference/math/functions/round.xml
  reference/math/functions/srand.xml
Labels: method synopsis

#662 Remove old install docs
  install/cloud/rackspace.xml
  install/fpm/configuration.xml
  install/ini.xml
  install/pecl.xml
  install/unix/apache1.xml
  install/unix/apache2.xml
  install/unix/hpux.xml
  install/unix/index.xml
  install/unix/openbsd.xml
  install/unix/solaris.xml
Labels: Waiting on Author

#889 Add documentation about the never type
  language/types/declarations.xml
Labels: next milestone

#361 Use 'ENT_QUOTES|ENT_SUBSTITUTE' for HTML encoding and decoding functions
  language/functions.xml
  reference/strings/functions/get-html-translation-table.xml
  reference/strings/functions/html-entity-decode.xml
  reference/strings/functions/htmlentities.xml
  reference/strings/functions/htmlspecialchars-decode.xml
  reference/strings/functions/htmlspecialchars.xml
Labels: next milestone

#436 rlimit constants update related to php 8.0.2 update
  reference/posix/constants.xml
Labels: next milestone

#967 [PHP 8.1] Use an `FTP\Connection` instance instead of a resource
  appendices/resources.xml
  language-snippets.ent
  reference/ftp/book.xml
  reference/ftp/examples.xml
  reference/ftp/ftp.connection.xml
  reference/ftp/functions/ftp-alloc.xml
  reference/ftp/functions/ftp-append.xml
  reference/ftp/functions/ftp-cdup.xml
  reference/ftp/functions/ftp-chdir.xml
  reference/ftp/functions/ftp-chmod.xml
  reference/ftp/functions/ftp-close.xml
  reference/ftp/functions/ftp-connect.xml
  reference/ftp/functions/ftp-delete.xml
  reference/ftp/functions/ftp-exec.xml
  reference/ftp/functions/ftp-fget.xml
  reference/ftp/functions/ftp-fput.xml
  reference/ftp/functions/ftp-get-option.xml
  reference/ftp/functions/ftp-get.xml
  reference/ftp/functions/ftp-login.xml
  reference/ftp/functions/ftp-mdtm.xml
  reference/ftp/functions/ftp-mkdir.xml
  reference/ftp/functions/ftp-mlsd.xml
  reference/ftp/functions/ftp-nb-continue.xml
  reference/ftp/functions/ftp-nb-fget.xml
  reference/ftp/functions/ftp-nb-fput.xml
  reference/ftp/functions/ftp-nb-get.xml
  reference/ftp/functions/ftp-nb-put.xml
  reference/ftp/functions/ftp-nlist.xml
  reference/ftp/functions/ftp-pasv.xml
  reference/ftp/functions/ftp-put.xml
  reference/ftp/functions/ftp-pwd.xml
  reference/ftp/functions/ftp-raw.xml
  reference/ftp/functions/ftp-rawlist.xml
  reference/ftp/functions/ftp-rename.xml
  reference/ftp/functions/ftp-rmdir.xml
  reference/ftp/functions/ftp-set-option.xml
  reference/ftp/functions/ftp-site.xml
  reference/ftp/functions/ftp-size.xml
  reference/ftp/functions/ftp-ssl-connect.xml
  reference/ftp/functions/ftp-systype.xml
  reference/ftp/setup.xml
  reference/ftp/versions.xml
Labels: next milestone

#978 [PHP 8.1] Update `fputcsv` and `SplFileObject::fputcsv` description
  reference/filesystem/functions/fputcsv.xml
  reference/spl/splfileobject/fputcsv.xml
Labels: next milestone

#971 [PHP 8.1] Use an `IMAP\Connection` instance instead of a resource
  appendices/resources.xml
  language-snippets.ent
  reference/imap/book.xml
  reference/imap/functions/imap-append.xml
  reference/imap/functions/imap-body.xml
  reference/imap/functions/imap-bodystruct.xml
  reference/imap/functions/imap-check.xml
  reference/imap/functions/imap-clearflag-full.xml
  reference/imap/functions/imap-close.xml
  reference/imap/functions/imap-createmailbox.xml
  reference/imap/functions/imap-delete.xml
  reference/imap/functions/imap-deletemailbox.xml
  reference/imap/functions/imap-expunge.xml
  reference/imap/functions/imap-fetch-overview.xml
  reference/imap/functions/imap-fetchbody.xml
  reference/imap/functions/imap-fetchheader.xml
  reference/imap/functions/imap-fetchmime.xml
  reference/imap/functions/imap-fetchstructure.xml
  reference/imap/functions/imap-gc.xml
  reference/imap/functions/imap-get-quota.xml
  reference/imap/functions/imap-get-quotaroot.xml
  reference/imap/functions/imap-getacl.xml
  reference/imap/functions/imap-getmailboxes.xml
  reference/imap/functions/imap-getsubscribed.xml
  reference/imap/functions/imap-headerinfo.xml
  reference/imap/functions/imap-headers.xml
  reference/imap/functions/imap-list.xml
  reference/imap/functions/imap-listscan.xml
  reference/imap/functions/imap-lsub.xml
  reference/imap/functions/imap-mail-copy.xml
  reference/imap/functions/imap-mail-move.xml
  reference/imap/functions/imap-mailboxmsginfo.xml
  reference/imap/functions/imap-msgno.xml
  reference/imap/functions/imap-num-msg.xml
  reference/imap/functions/imap-num-recent.xml
  reference/imap/functions/imap-open.xml
  reference/imap/functions/imap-ping.xml
  reference/imap/functions/imap-renamemailbox.xml
  reference/imap/functions/imap-reopen.xml
  reference/imap/functions/imap-savebody.xml
  reference/imap/functions/imap-search.xml
  reference/imap/functions/imap-set-quota.xml
  reference/imap/functions/imap-setacl.xml
  reference/imap/functions/imap-setflag-full.xml
  reference/imap/functions/imap-sort.xml
  reference/imap/functions/imap-status.xml
  reference/imap/functions/imap-subscribe.xml
  reference/imap/functions/imap-thread.xml
  reference/imap/functions/imap-uid.xml
  reference/imap/functions/imap-undelete.xml
  reference/imap/functions/imap-unsubscribe.xml
  reference/imap/imap.connection.xml
  reference/imap/setup.xml
  reference/imap/versions.xml
Labels: next milestone

#985 [PHP 8.1] Use an `finfo` instance instead of a resource
  language-snippets.ent
  reference/fileinfo/functions/finfo-buffer.xml
  reference/fileinfo/functions/finfo-close.xml
  reference/fileinfo/functions/finfo-file.xml
  reference/fileinfo/functions/finfo-open.xml
  reference/fileinfo/functions/finfo-set-flags.xml
  reference/fileinfo/setup.xml
Labels: Waiting on Review, next milestone

#983 [PHP 8.1] Add `imageavif` and `imagecreatefromavif` functions
  reference/image/functions/imageavif.xml
  reference/image/functions/imagecreatefromavif.xml
  reference/image/versions.xml
Labels: Waiting on Review, next milestone

#975 [PHP 8.1] Use an LDAP instance instead of a resource
  appendices/resources.xml
  language-snippets.ent
  reference/ldap/book.xml
  reference/ldap/functions/ldap-add-ext.xml
  reference/ldap/functions/ldap-add.xml
  reference/ldap/functions/ldap-bind-ext.xml
  reference/ldap/functions/ldap-bind.xml
  reference/ldap/functions/ldap-compare.xml
  reference/ldap/functions/ldap-connect.xml
  reference/ldap/functions/ldap-control-paged-result-response.xml
  reference/ldap/functions/ldap-control-paged-result.xml
  reference/ldap/functions/ldap-count-entries.xml
  reference/ldap/functions/ldap-count-references.xml
  reference/ldap/functions/ldap-delete-ext.xml
  reference/ldap/functions/ldap-delete.xml
  reference/ldap/functions/ldap-errno.xml
  reference/ldap/functions/ldap-error.xml
  reference/ldap/functions/ldap-exop-passwd.xml
  reference/ldap/functions/ldap-exop-refresh.xml
  reference/ldap/functions/ldap-exop-whoami.xml
  reference/ldap/functions/ldap-exop.xml
  reference/ldap/functions/ldap-first-attribute.xml
  reference/ldap/functions/ldap-first-entry.xml
  reference/ldap/functions/ldap-first-reference.xml
  reference/ldap/functions/ldap-free-result.xml
  reference/ldap/functions/ldap-get-attributes.xml
  reference/ldap/functions/ldap-get-dn.xml
  reference/ldap/functions/ldap-get-entries.xml
  reference/ldap/functions/ldap-get-option.xml
  reference/ldap/functions/ldap-get-values-len.xml
  reference/ldap/functions/ldap-get-values.xml
  reference/ldap/functions/ldap-list.xml
  reference/ldap/functions/ldap-mod-add-ext.xml
  reference/ldap/functions/ldap-mod-add.xml
  reference/ldap/functions/ldap-mod-del-ext.xml
  reference/ldap/functions/ldap-mod-del.xml
  reference/ldap/functions/ldap-mod-replace-ext.xml
  reference/ldap/functions/ldap-mod-replace.xml
  reference/ldap/functions/ldap-modify-batch.xml
  reference/ldap/functions/ldap-next-attribute.xml
  reference/ldap/functions/ldap-next-entry.xml
  reference/ldap/functions/ldap-next-reference.xml
  reference/ldap/functions/ldap-parse-exop.xml
  reference/ldap/functions/ldap-parse-reference.xml
  reference/ldap/functions/ldap-parse-result.xml
  reference/ldap/functions/ldap-read.xml
  reference/ldap/functions/ldap-rename-ext.xml
  reference/ldap/functions/ldap-rename.xml
  reference/ldap/functions/ldap-sasl-bind.xml
  reference/ldap/functions/ldap-search.xml
  reference/ldap/functions/ldap-set-option.xml
  reference/ldap/functions/ldap-set-rebind-proc.xml
  reference/ldap/functions/ldap-sort.xml
  reference/ldap/functions/ldap-start-tls.xml
  reference/ldap/functions/ldap-unbind.xml
  reference/ldap/ldap.connection.xml
  reference/ldap/ldap.result.xml
  reference/ldap/ldap.resultentry.xml
  reference/ldap/setup.xml
  reference/ldap/versions.xml
Labels: Waiting on Review, next milestone
