Repository php/doc-en, pull requests merged in 2022-11, with the labels that each got.

#435 [apcu] Clarify the effect of apc.ttl
  reference/apcu/ini.xml
Labels: Waiting on Review

#1597 Sync ext/date class synopsis with recent stub changes
  reference/datetime/constants.xml
  reference/datetime/dateperiod.xml
  reference/datetime/datetime.xml
  reference/datetime/datetimeimmutable.xml
  reference/datetime/datetimeinterface.xml
  reference/datetime/datetimeinterface/format.xml
  reference/datetime/datetimezone.xml
  reference/datetime/functions/date.xml
Labels: Waiting on Author, method synopsis

#1267 Update the signature of dba_open() and dba_popen()
  reference/dba/functions/dba-open.xml
  reference/dba/functions/dba-popen.xml
Labels: method synopsis

#2021 Adapt to current OpenBSD version
  install/unix/openbsd.xml
Labels: Waiting on Author

#1726 Rewrite type section
  appendices/migration81/new-features.xml
  language/oop5/properties.xml
  language/oop5/variance.xml
  language/types.xml
  language/types/boolean.xml
  language/types/declarations.xml
  language/types/integer.xml
  language/types/iterable.xml
  language/types/literal.xml
  language/types/mixed.xml
  language/types/never.xml
  language/types/null.xml
  language/types/relative-class-types.xml
  language/types/string.xml
  language/types/type-juggling.xml
  language/types/type-system.xml
  language/types/void.xml
Labels: mahoosive-change
