Repository php/doc-en, pull requests merged in 2022-05, with the labels that each got.

#1560 [PHP 8.1] Return Type Compatibility with Internal Classes
  language/oop5/inheritance.xml
Labels: Waiting on Review

#1587 Fix: `Ds\Collection` extends `IteratorAggregate`.
  reference/ds/ds.collection.xml
Labels: duplicate

#1599 Sync ext/tidy properties with stubs
  reference/tidy/tidy.xml
  reference/tidy/tidynode.xml
Labels: method synopsis
