Repository php/doc-en, pull requests merged in 2022-04, with the labels that each got.

#1196 Fixed info about @ operator
  appendices/migration80/incompatible.xml
  language/operators.xml
  reference/errorfunc/functions/set-error-handler.xml
Labels: Waiting on Author

#1503 Clean up autoload page
  language/oop5/autoload.xml
Labels: Waiting on Review

#911 Generate ext/intl methodsynopses based on stubs (IntlTimeZone)
  reference/intl/intltimezone/countequivalentids.xml
  reference/intl/intltimezone/createdefault.xml
  reference/intl/intltimezone/createenumeration.xml
  reference/intl/intltimezone/createtimezone.xml
  reference/intl/intltimezone/createtimezoneidenumeration.xml
  reference/intl/intltimezone/fromdatetimezone.xml
  reference/intl/intltimezone/getcanonicalid.xml
  reference/intl/intltimezone/getdisplayname.xml
  reference/intl/intltimezone/getdstsavings.xml
  reference/intl/intltimezone/getequivalentid.xml
  reference/intl/intltimezone/geterrorcode.xml
  reference/intl/intltimezone/geterrormessage.xml
  reference/intl/intltimezone/getgmt.xml
  reference/intl/intltimezone/getid.xml
  reference/intl/intltimezone/getidforwindowsid.xml
  reference/intl/intltimezone/getoffset.xml
  reference/intl/intltimezone/getrawoffset.xml
  reference/intl/intltimezone/getregion.xml
  reference/intl/intltimezone/gettzdataversion.xml
  reference/intl/intltimezone/getunknown.xml
  reference/intl/intltimezone/getwindowsid.xml
  reference/intl/intltimezone/hassamerules.xml
  reference/intl/intltimezone/todatetimezone.xml
  reference/intl/intltimezone/usedaylighttime.xml
Labels: method synopsis

#905 Generate methodsynopses for ext/intl (idna, IntlChar)
  language-snippets.ent
  reference/intl/idn/idn-to-utf8.xml
  reference/intl/intlchar/charage.xml
  reference/intl/intlchar/chardigitvalue.xml
  reference/intl/intlchar/chardirection.xml
  reference/intl/intlchar/charfromname.xml
  reference/intl/intlchar/charmirror.xml
  reference/intl/intlchar/charname.xml
  reference/intl/intlchar/chr.xml
  reference/intl/intlchar/digit.xml
  reference/intl/intlchar/enumcharnames.xml
  reference/intl/intlchar/foldcase.xml
  reference/intl/intlchar/fordigit.xml
  reference/intl/intlchar/getbidipairedbracket.xml
  reference/intl/intlchar/getblockcode.xml
  reference/intl/intlchar/getcombiningclass.xml
  reference/intl/intlchar/getfc-nfkc-closure.xml
  reference/intl/intlchar/getintpropertyvalue.xml
  reference/intl/intlchar/getnumericvalue.xml
  reference/intl/intlchar/getpropertyname.xml
  reference/intl/intlchar/getpropertyvaluename.xml
  reference/intl/intlchar/hasbinaryproperty.xml
  reference/intl/intlchar/isalnum.xml
  reference/intl/intlchar/isalpha.xml
  reference/intl/intlchar/isbase.xml
  reference/intl/intlchar/isblank.xml
  reference/intl/intlchar/iscntrl.xml
  reference/intl/intlchar/isdefined.xml
  reference/intl/intlchar/isdigit.xml
  reference/intl/intlchar/isgraph.xml
  reference/intl/intlchar/isidignorable.xml
  reference/intl/intlchar/isidpart.xml
  reference/intl/intlchar/isidstart.xml
  reference/intl/intlchar/isisocontrol.xml
  reference/intl/intlchar/isjavaidpart.xml
  reference/intl/intlchar/isjavaidstart.xml
  reference/intl/intlchar/isjavaspacechar.xml
  reference/intl/intlchar/islower.xml
  reference/intl/intlchar/ismirrored.xml
  reference/intl/intlchar/isprint.xml
  reference/intl/intlchar/ispunct.xml
  reference/intl/intlchar/isspace.xml
  reference/intl/intlchar/istitle.xml
  reference/intl/intlchar/isualphabetic.xml
  reference/intl/intlchar/isulowercase.xml
  reference/intl/intlchar/isupper.xml
  reference/intl/intlchar/isuuppercase.xml
  reference/intl/intlchar/isuwhitespace.xml
  reference/intl/intlchar/iswhitespace.xml
  reference/intl/intlchar/isxdigit.xml
  reference/intl/intlchar/ord.xml
  reference/intl/intlchar/tolower.xml
  reference/intl/intlchar/totitle.xml
  reference/intl/intlchar/toupper.xml
Labels: method synopsis

#1045 [PHP 8.1] Add new sodium functions
  reference/sodium/functions/sodium-crypto-stream-xchacha20-keygen.xml
  reference/sodium/functions/sodium-crypto-stream-xchacha20-xor.xml
  reference/sodium/functions/sodium-crypto-stream-xchacha20.xml
  reference/sodium/versions.xml
Labels: Waiting on Review

#1051 [PHP 8.1] Add sodium ristretto255 functions
  reference/sodium/functions/sodium-crypto-core-ristretto255-add.xml
  reference/sodium/functions/sodium-crypto-core-ristretto255-from-hash.xml
  reference/sodium/functions/sodium-crypto-core-ristretto255-is-valid-point.xml
  reference/sodium/functions/sodium-crypto-core-ristretto255-random.xml
  reference/sodium/functions/sodium-crypto-core-ristretto255-scalar-add.xml
  reference/sodium/functions/sodium-crypto-core-ristretto255-scalar-complement.xml
  reference/sodium/functions/sodium-crypto-core-ristretto255-scalar-invert.xml
  reference/sodium/functions/sodium-crypto-core-ristretto255-scalar-mul.xml
  reference/sodium/functions/sodium-crypto-core-ristretto255-scalar-negate.xml
  reference/sodium/functions/sodium-crypto-core-ristretto255-scalar-random.xml
  reference/sodium/functions/sodium-crypto-core-ristretto255-scalar-reduce.xml
  reference/sodium/functions/sodium-crypto-core-ristretto255-scalar-sub.xml
  reference/sodium/functions/sodium-crypto-core-ristretto255-sub.xml
  reference/sodium/functions/sodium-crypto-scalarmult-ristretto255-base.xml
  reference/sodium/functions/sodium-crypto-scalarmult-ristretto255.xml
  reference/sodium/versions.xml
Labels: Waiting on Review

#1335 Reorder DOMDocument properties
  reference/dom/domdocument.xml
Labels: method synopsis

#1295 Sync ext/dom properties with stubs - part 1
  reference/dom/domattr.xml
  reference/dom/domcharacterdata.xml
  reference/dom/domdocumentfragment.xml
  reference/dom/domdocumenttype.xml
  reference/dom/domentity.xml
  reference/dom/domxpath.xml
Labels: method synopsis, Waiting on Review

#1297 Sync ext/dom properties with stubs - part 2
  reference/dom/domelement.xml
Labels: method synopsis, Waiting on Review

#1531 Adjust formatting of intldatepatterngenerator.xml according to gen_stub.php
  reference/intl/intldatepatterngenerator.xml
Labels: method synopsis

#1549 [PHP 8.1] Usage of static Variables in Inherited Methods
  language/variables.xml
Labels: Waiting on Review

#1032 [PHP 8.1] Add ReflectionFunctionAbstract::getClosureUsedVariables
  reference/reflection/reflectionfunctionabstract/getclosureusedvariables.xml
  reference/reflection/versions.xml
Labels: Waiting on Review
