Repository php/doc-en, pull requests merged in 2022-03, with the labels that each got.

#958 Add `pcntl_unshare` description
  reference/pcntl/constants.xml
  reference/pcntl/functions/pcntl-unshare.xml
  reference/pcntl/versions.xml
Labels: Waiting on Review

#1465 Fix constructorsynopsis usage in EV extension
  reference/ev/evcheck.xml
  reference/ev/evcheck/construct.xml
  reference/ev/evchild.xml
  reference/ev/evchild/construct.xml
  reference/ev/evembed.xml
  reference/ev/evembed/construct.xml
  reference/ev/evfork.xml
  reference/ev/evfork/construct.xml
  reference/ev/evidle.xml
  reference/ev/evidle/construct.xml
  reference/ev/evio.xml
  reference/ev/evio/construct.xml
  reference/ev/evloop.xml
  reference/ev/evloop/construct.xml
  reference/ev/evperiodic.xml
  reference/ev/evperiodic/construct.xml
  reference/ev/evprepare.xml
  reference/ev/evprepare/construct.xml
  reference/ev/evsignal.xml
  reference/ev/evsignal/construct.xml
  reference/ev/evstat.xml
  reference/ev/evstat/construct.xml
  reference/ev/evtimer.xml
  reference/ev/evtimer/construct.xml
  reference/ev/evwatcher.xml
  reference/ev/evwatcher/construct.xml
Labels: QA

#1327 [PHP 8.1] New in initializers
  language/oop5/decon.xml
Labels: Waiting on Review

#1026 [PHP 8.1] Add IntlDatePatternGenerator description
  reference/intl/book.xml
  reference/intl/intldatepatterngenerator.xml
  reference/intl/intldatepatterngenerator/create.xml
  reference/intl/intldatepatterngenerator/getbestpattern.xml
  reference/intl/versions.xml
Labels: Waiting on Review

#1329 [PHP 8.1] Use named arguments after unpacking
  language/functions.xml
Labels: Waiting on Review

#850 Fix array_combine throws ValueError since PHP 8
  reference/array/functions/array-combine.xml
Labels: Waiting on Review

#1293 Sync DirectoryIterator method return types
  reference/spl/directoryiterator/current.xml
  reference/spl/directoryiterator/key.xml
Labels: method synopsis

#1477 Add examples for string functions
  reference/strings/functions/bin2hex.xml
  reference/strings/functions/nl-langinfo.xml
  reference/strings/functions/quoted-printable-decode.xml
  reference/strings/functions/quoted-printable-encode.xml
  reference/strings/functions/quotemeta.xml
  reference/strings/functions/str-getcsv.xml
  reference/strings/functions/stripcslashes.xml
  reference/strings/functions/strnatcasecmp.xml
  reference/strings/functions/strncasecmp.xml
  reference/strings/functions/strncmp.xml
Labels: Waiting on Review
