Repository php/doc-en, pull requests merged in 2023-01, with the labels that each got.

#2126 Add documentation for missing attribute constructors
  appendices/migration82/new-features.xml
  language/predefined/allowdynamicproperties/construct.xml
  language/predefined/attribute/construct.xml
  language/predefined/attributes.xml
  language/predefined/attributes/allowdynamicproperties.xml
  language/predefined/attributes/attribute.xml
  language/predefined/attributes/returntypewillchange.xml
  language/predefined/attributes/sensitiveparameter.xml
  language/predefined/returntypewillchange/construct.xml
  language/predefined/sensitiveparameter/construct.xml
  language/predefined/versions.xml
Labels: method synopsis

#2146 Add missing ext/intl class constants with empty description
  reference/intl/collator-constants.xml
  reference/intl/collator.xml
  reference/intl/dateformatter-constants.xml
  reference/intl/dateformatter.xml
  reference/intl/intlchar.xml
  reference/intl/intltimezone.xml
  reference/intl/locale-constants.xml
  reference/intl/locale.xml
  reference/intl/normalizer-constants.xml
  reference/intl/normalizer.xml
  reference/intl/numberformatter-constants.xml
  reference/intl/numberformatter.xml
  reference/intl/spoofchecker.xml
Labels: method synopsis

#2151 Remove unnecessary documentation
  reference/soap/soapserver.xml
  reference/spl/spldoublylinkedlist/setiteratormode.xml
  reference/spl/splqueue/setiteratormode.xml
  reference/spl/splstack.xml
  reference/spl/splstack/setiteratormode.xml
Labels: method synopsis

#2160 Add missing class constants with empty description - part 4
  reference/snmp/snmp.xml
  reference/spl/splpriorityqueue.xml
Labels: method synopsis

#2170 Document the __toString() and export() related changes in ext/reflection
  reference/reflection/reflectionclass.xml
  reference/reflection/reflectionclassconstant.xml
  reference/reflection/reflectionextension.xml
  reference/reflection/reflectionfunction.xml
  reference/reflection/reflectionmethod.xml
  reference/reflection/reflectionobject.xml
  reference/reflection/reflectionparameter.xml
  reference/reflection/reflectionproperty.xml
  reference/reflection/reflectionzendextension.xml
  reference/reflection/reflector.xml
  reference/reflection/reflector/tostring.xml
  reference/reflection/versions.xml
  reference/spl/versions.xml
Labels: method synopsis

#596 Redesign parameter list for PDO_Statement::fetchAll
  reference/pdo/pdostatement/fetchall.xml
Labels: Waiting on Review

#2206 Remove some mysqli_driver properties and methods
  reference/mysqli/ini.xml
  reference/mysqli/mysqli_driver.xml
Labels: method synopsis

#1621 Add note that ReflectionProperty::getDefaultValue() does not copy from promoted property
  language/oop5/decon.xml
  reference/reflection/reflectionproperty/getdefaultvalue.xml
Labels: Waiting on Review

#1693 added quotes around literal dot to diferntiate it from the full stop following imediatly after.
  language/types/string.xml
Labels: Waiting on Review

#1036 Make password_needs_rehash() more prominent
  reference/password/functions/password-hash.xml
  reference/password/functions/password-verify.xml
Labels: Waiting on Author

#1413 document ext-mysqli exception throwing on their respective pages
  language-snippets.ent
  reference/mysqli/mysqli/autocommit.xml
  reference/mysqli/mysqli/change-user.xml
  reference/mysqli/mysqli/commit.xml
  reference/mysqli/mysqli/construct.xml
  reference/mysqli/mysqli/kill.xml
  reference/mysqli/mysqli/multi-query.xml
  reference/mysqli/mysqli/next-result.xml
  reference/mysqli/mysqli/options.xml
  reference/mysqli/mysqli/ping.xml
  reference/mysqli/mysqli/prepare.xml
  reference/mysqli/mysqli/query.xml
  reference/mysqli/mysqli/real-connect.xml
  reference/mysqli/mysqli/real-query.xml
  reference/mysqli/mysqli/reap-async-query.xml
  reference/mysqli/mysqli/rollback.xml
  reference/mysqli/mysqli/select-db.xml
  reference/mysqli/mysqli/set-charset.xml
  reference/mysqli/mysqli/store-result.xml
  reference/mysqli/mysqli/use-result.xml
  reference/mysqli/mysqli_result/construct.xml
  reference/mysqli/mysqli_stmt/attr-set.xml
  reference/mysqli/mysqli_stmt/bind-param.xml
  reference/mysqli/mysqli_stmt/construct.xml
  reference/mysqli/mysqli_stmt/execute.xml
  reference/mysqli/mysqli_stmt/fetch.xml
  reference/mysqli/mysqli_stmt/get-result.xml
  reference/mysqli/mysqli_stmt/next-result.xml
  reference/mysqli/mysqli_stmt/prepare.xml
  reference/mysqli/mysqli_stmt/result-metadata.xml
  reference/mysqli/mysqli_stmt/store-result.xml
Labels: Waiting on Review
