Repository php/doc-en, pull requests merged in 2023-07, with the labels that each got.

#2598 [PHP 8.2] Added PCRE n (NO_AUTO_CAPTURE) modifier description.
  reference/pcre/pattern.modifiers.xml
Labels: Extension: pcre

#1798 ArrayAccess:: method need a return type
  language/predefined/arrayaccess.xml
Labels: Waiting on Author, Waiting on Review

#1630 Add note explaining the bitmap combination possiblities
  reference/errorfunc/functions/debug-backtrace.xml
Labels: question
