Repository php/doc-en, pull requests merged in 2023-09, with the labels that each got.

#2659 Fix GH-2655: add `PEM`, `PKCS`, `CSR` and `DER` acronyms
  appendices/migration56/openssl.xml
  appendices/migration80/new-features.xml
  appendices/migration81/incompatible.xml
  language/context/ssl.xml
  reference/event/eventsslcontext.xml
  reference/mongodb/mongodb/driver/manager/construct.xml
  reference/mysqli/mysqli/ssl-set.xml
  reference/openssl/certparams.xml
  reference/openssl/constants.xml
  reference/openssl/functions/openssl-cms-decrypt.xml
  reference/openssl/functions/openssl-cms-read.xml
  reference/openssl/functions/openssl-csr-export-to-file.xml
  reference/openssl/functions/openssl-csr-export.xml
  reference/openssl/functions/openssl-csr-get-public-key.xml
  reference/openssl/functions/openssl-csr-get-subject.xml
  reference/openssl/functions/openssl-csr-new.xml
  reference/openssl/functions/openssl-csr-sign.xml
  reference/openssl/functions/openssl-pkcs12-export-to-file.xml
  reference/openssl/functions/openssl-pkcs12-export.xml
  reference/openssl/functions/openssl-pkcs12-read.xml
  reference/openssl/functions/openssl-pkcs7-read.xml
  reference/openssl/functions/openssl-pkcs7-verify.xml
  reference/openssl/functions/openssl-pkey-export-to-file.xml
  reference/openssl/functions/openssl-pkey-export.xml
  reference/openssl/functions/openssl-pkey-get-private.xml
  reference/openssl/functions/openssl-pkey-get-public.xml
  reference/openssl/functions/openssl-sign.xml
  reference/openssl/functions/openssl-spki-export.xml
  reference/openssl/functions/openssl-spki-new.xml
  reference/openssl/functions/openssl-verify.xml
  reference/openssl/functions/openssl-x509-checkpurpose.xml
  reference/openssl/functions/openssl-x509-export-to-file.xml
  reference/openssl/functions/openssl-x509-export.xml
  reference/openssl/functions/openssl-x509-verify.xml
  reference/pdo_mysql/constants.xml
  reference/soap/soapclient/construct.xml
Labels: QA

#2725 Add ctype functions to IntlChar's "see also" section and vice versa
  reference/ctype/functions/ctype-alnum.xml
  reference/ctype/functions/ctype-alpha.xml
  reference/ctype/functions/ctype-cntrl.xml
  reference/ctype/functions/ctype-digit.xml
  reference/ctype/functions/ctype-graph.xml
  reference/ctype/functions/ctype-lower.xml
  reference/ctype/functions/ctype-print.xml
  reference/ctype/functions/ctype-punct.xml
  reference/ctype/functions/ctype-space.xml
  reference/ctype/functions/ctype-upper.xml
  reference/ctype/functions/ctype-xdigit.xml
  reference/intl/intlchar/isalnum.xml
  reference/intl/intlchar/isalpha.xml
  reference/intl/intlchar/iscntrl.xml
  reference/intl/intlchar/isdigit.xml
  reference/intl/intlchar/isgraph.xml
  reference/intl/intlchar/islower.xml
  reference/intl/intlchar/isprint.xml
  reference/intl/intlchar/ispunct.xml
  reference/intl/intlchar/isspace.xml
  reference/intl/intlchar/isupper.xml
  reference/intl/intlchar/isxdigit.xml
Labels: QA

#2755 Clarify constructor property promotion modifiers
  language/oop5/decon.xml
Labels: bug, Status: Verified

#2766 Fix SimpleXMLElement::current() example
  reference/simplexml/simplexmlelement/current.xml
Labels: Extension: SimpleXml
