Repository php/doc-en, pull requests merged in 2024-09, with the labels that each got.

#2717 Standardise casting spacing
  appendices/migration72/incompatible.xml
  chapters/tutorial.xml
  language/operators/bitwise.xml
  language/operators/comparison.xml
  language/types/array.xml
  language/types/integer.xml
  reference/array/functions/array-merge.xml
  reference/datetime/datetimeinterface/gettimestamp.xml
  reference/ffi/examples.xml
  reference/mongodb/mongodb/driver/command.xml
  reference/rar/examples.xml
  reference/reflection/reflectionenum/getbackingtype.xml
  reference/session/sessionhandlerinterface.xml
  reference/stream/functions/stream-notification-callback.xml
Labels: QA

#3560 constants.xml: add dots at the end of sentences
  reference/mysqli/constants.xml
Labels: QA

#3466 Added info about invert property
  reference/datetime/datetimeinterface/diff.xml
Labels: Extension: date

#2037 Fix return value description of Imagick::getResourceLimit
  reference/imagick/imagick/getresourcelimit.xml
Labels: Waiting on Review, Extension: Imagick

#1524 Document where wordwrap() wraps
  reference/strings/functions/wordwrap.xml
Labels: Waiting on Author
